name: pgai
services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=geneseslabs
      - POSTGRES_PASSWORD=geneseslabs
      - POSTGRES_DB=geneseslabs
    ports:
      - "5499:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: